### ISSUE TITLE
Map Loading

### ISSUE THREAD

**Issue by ygina** [battlecode/battlecode-scaffold-2017#14]
Takes a looooong time.

**Comment by Kushal-sophos** [comment]
Agreed, and so does loading the list of players and the list of maps. :( Last year's specs were much faster in comparison.

**Comment by shubham418** [comment]
And also new maps require restarting the program.

**Comment by vontell** [comment]
Map loading is now much faster! @shubham418 this is a good point; I will work on adding a refresh button to the client: see https://github.com/battlecode/battlecode-client-17/issues/105

**Comment by vontell** [comment]
Closing this as the refreshing issue is within client.
