### ISSUE TITLE
Gradle + offline = bad

### ISSUE THREAD

**Issue by veswill3** [battlecode/battlecode-scaffold-2017#17]
I am currently traveling and I have spotty access to Internet at best. While I had internet last I made sure everything was up to date and working, but when I opened eclipse later that day, no luck. Reading through the Gradle output it is failing because it cannot update from the battlcode server.

I can appreciate wanting to keep everything up to date, but could it at least fall back to the previously downloaded dependencies? Alternatively, could someone show me how to temporarily edit the the config so I can work offline until I get internet again?

**Comment by zhjch05** [comment]
I have the same question, I am currently out of US and every time I need to redownload the client again. Is there anyway to let gradle work offline temporarily? I can just use non-lastest client for a while. Or if, I get use some software to indirectly download the client zip file, can I get a chance to manually unpack and intall it or let gradle recognize it?

**Comment by emabrey** [comment]
Are you running gradle with the offline option? 

aka `gradlew run --offline`?

**Comment by kazimuth** [comment]
Yeah, see https://docs.gradle.org/current/userguide/userguide_single.html#sub:cache_offline

I'm not sure how to tell eclipse / intellij to run like that, though. Maybe there's an option in some menu?

**Comment by veswill3** [comment]
`--offline` will work great for a temporary solution. Thanks!

I did find a way to use that in eclipse, but it is a hassle and I am sure there is a better way:

1. right click the task
2. `Open Gradle Run Configuration...`
3. arguments tab
4. enter `--offline` in the `Program Arguments` field
5. click ok
6. rerun the task.

That is per task and would forever disalbe updates unless you remove the parameter. I am going to stick to the command line.

This issue is resolved for me, but should we update the README or add something to the `build.gradle` to handle it more gracefully? Otherwise we can just close this issue.

**Comment by zhjch05** [comment]
Thanks! `--offline` should work but sadly offline mode ask for 1.1.7 cache but I only have 1.1.1 client. But I am back in US soon.
